language: csharp
solution: WebApp/WebApp.sln

before_install:
  - git config credential.helper "store --file=.git/credentials"; echo "https://7ae54e057f2c018e277ceb9f565b0122ecb72b45:@github.com" > .git/credentials 2>/dev/null
  - git config --global user.email "yuriferre@gmail.com"
  - git config --global user.name "yuri"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: 7ae54e057f2c018e277ceb9f565b0122ecb72b45
  on:
    branch: master
